### ISSUE TITLE
Failed to open APK: I/O error

### ISSUE THREAD

**Issue by pnewell** [scade-platform/FusionExamples#13]
When I try to Build/Debug either of the new examples, `SwiftAndroidGithubApiExample` or `SwiftCryptoAndroidExample`, it builds and installs successfully but then never launches and spits out the following errors:

```
Failed to open APK '/data/app/~~Xqz8KIvSoxmPylAp28xadw==/com.example.swiftandroidexample-HpVY9E5H435ZDBe8dvdoIg==/base.apk': I/O error
2023-10-26 11:10:35.396  1433-1571  .apps.wellbeing         com.google.android.apps.wellbeing    E  Failed to open APK '/data/app/~~Xqz8KIvSoxmPylAp28xadw==/com.example.swiftandroidexample-HpVY9E5H435ZDBe8dvdoIg==/base.apk': I/O error
2023-10-26 11:10:35.397  1433-1571  ResourcesManager        com.google.android.apps.wellbeing    E  failed to add asset path '/data/app/~~Xqz8KIvSoxmPylAp28xadw==/com.example.swiftandroidexample-HpVY9E5H435ZDBe8dvdoIg==/base.apk'
                                                                                                    java.io.IOException: Failed to load asset path /data/app/~~Xqz8KIvSoxmPylAp28xadw==/com.example.swiftandroidexample-HpVY9E5H435ZDBe8dvdoIg==/base.apk
                                                                                                    	at android.content.res.ApkAssets.nativeLoad(Native Method)
                                                                                                    	at android.content.res.ApkAssets.<init>(ApkAssets.java:298)
                                                                                                    	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:147)
                                                                                                    	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:474)
                                                                                                    	at android.app.ResourcesManager.-$$Nest$mloadApkAssets(Unknown Source:0)
                                                                                                    	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:167)
                                                                                                    	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:550)
                                                                                                    	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:637)
                                                                                                    	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:689)
                                                                                                    	at android.app.ResourcesManager.createResources(ResourcesManager.java:1035)
                                                                                                    	at android.app.ResourcesManager.getResources(ResourcesManager.java:1138)
                                                                                                    	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2597)
                                                                                                    	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:2060)
                                                                                                    	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:2046)
                                                                                                    	at android.app.ApplicationPackageManager.getText(ApplicationPackageManager.java:2363)
                                                                                                    	at android.content.pm.PackageItemInfo.loadUnsafeLabel(PackageItemInfo.java:222)
                                                                                                    	at android.content.pm.PackageItemInfo.loadLabel(PackageItemInfo.java:212)
                                                                                                    	at android.app.ApplicationPackageManager.getApplicationLabel(ApplicationPackageManager.java:2408)
                                                                                                    	at crm.f(PG:6)
                                                                                                    	at cdm.apply(PG:74)
                                                                                                    	at j$.util.stream.i.accept(SourceFile:27)
                                                                                                    	at j$.util.stream.P0.accept(SourceFile:3)
                                                                                                    	at j$.util.a.forEachRemaining(SourceFile:20)
                                                                                                    	at j$.util.stream.c.v(SourceFile:21)
                                                                                                    	at j$.util.stream.c.C(SourceFile:8)
                                                                                                    	at j$.util.stream.I0.e(SourceFile:1)
                                                                                                    	at j$.util.stream.c.F(SourceFile:35)
                                                                                                    	at j$.util.stream.g1.collect(SourceFile:83)
                                                                                                    	at bsv.a(PG:14)
                                                                                                    	at jza.a(PG:30)
                                                                                                    	at jza.a(PG:42)
                                                                                                    	at lne.a(PG:1)
                                                                                                    	at lmk.run(PG:4)
                                                                                                    	at lng.run(PG:1)
                                                                                                    	at llo.run(PG:3)
                                                                                                    	at idn.run(PG:5)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at huo.run(PG:51)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	at idx.run(PG:5)
```

**Comment by 6vedant** [comment]
Hi @pnewell ,

Apologies for late reply.

Can you do Try `File -> Invalidate caches & restart`
